schemaVersion: 2.1.0
metadata:
  name: developer-images
attributes:
  controller.devfile.io/scc: container-build
components:
  - name: devtools
    container:
      image: quay.io/devfile/universal-developer-image:ubi8-latest
      memoryLimit: 4Gi
      memoryRequest: 256Mi
