schemaVersion: 2.3.0
metadata:
  name: developer-images
attributes:
  controller.devfile.io/storage-type: ephemeral
  controller.devfile.io/scc: container-build
components:
  - name: devtools
    container:
      image: quay.io/devfile/universal-developer-image:ubi9-latest
      memoryLimit: 6Gi
      memoryRequest: 256Mi
